version: "2"

linters:
  default: none

  enable:
    - checkislower
    - checklanguage
    - checksensitivedata
    - checkspecialcharactersoremoji

  settings:
    custom:
      checkislower:
        type: module
        description: Linter to check for lowercase letters at the beginning of a message.
      checklanguage:
        type: module
        description: Linter to check that the text is in English.
      checksensitivedata:
        type: module
        description: Linter for checking sensitive data.
      checkspecialcharactersoremoji:
        type: module
        description: Linter for checking for special characters and emoji.
